{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "GetToken"
	},
	"ShowActivityIndicator": true,
	"Target": {
		"Service": "/DocInfoExtraction/Services/TokenSrv.service",
		"Path": "/",
		"RequestProperties": {
			"Method": "POST",
			"Headers": {
				"Content-Type": "application/x-www-form-urlencoded"
			},
			"Body": {
				"grant_type":"client_credentials",
				"client_id":"sb-c449dcc6-b937-49c1-96ca-2a5aa97cedef!b371911|dox-xsuaa-std-trial!b10844",
				"client_secret":"d80a74f9-6663-4ce0-a7c4-c24f7581dbf9$oultjgETDSk8g-w8g-V6sWPqLH7h-HbFqKjNeoc-kTo=",
				"new_token":"true"
			},"FetchCSRF": false
		}
	}
}